name: Publish
on:
  push:
    branches:
      - logging_v0604

jobs:
  publish_overwatch:
    name: Assembly spark3 JAR and copy to s3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run sbt assembly command
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: |
          sbt 'set test in assembly := {}' assembly
      - name: Copy jar to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DATA_ENG_CI_CD_KEY_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DATA_ENG_CI_CD_SECRET_PROD }}
        run: |
          aws s3 cp target/scala-2.11/overwatch-assembly-0.6.0.4.jar s3://scribd-data-eng-artifacts-prod/overwatch/overwatch-assembly-0.6.0.4.jar