baseURL = "https://tomesdata.z20.web.core.windows.net/"
title = "Overwatch"
theme = "hugo-theme-learn-2.5.0"

pluralizeListTitles = false

[params]
    description = "Overwatch Documentation"
    themeVariant = "blue"
    DisableShortcutsTitle = "true"
    author = "Daniel Tomes -- DatabricksLabs"